### PR TITLE
Update pipeline-start.png

### PR DESCRIPTION
**Pull request by mtspn**
update image to avoid confusion (old image showed ssh key path secret in the config)

### CODE REVIEW

**Review by ShellyXueHan — COMMENTED** [review]
I thought we've moved to use Github PAT and thus a HTTPS github URL is needed, or is this a different thing?

**Comment by mtspn** [comment]
Thanks @ShellyXueHan , this update was to remove something else. But good point, I just tested and with the changes here it doesn't work as shown. The repoURL was previously `git@github.com:bcgov/pipeline-templates.git`, what should i change it to for https?

**Comment by ShellyXueHan** [comment]
it would be `https://github.com/bcgov/pipeline-templates.git`. you can find the link by clicking on the green `Code` button and choose HTTPS for git clone.

**Comment by mtspn** [comment]
Thanks Shelly, I'd tried that in testing but was running into errors. Looks like it was due to the storage also needing to increase to 100Mi compared with the old version of the lab. This should be fixed in this new image.

**Pull request merged**
